# Copyright (c) 2022-2026, bageyelet

import re
import os

script_folder = os.path.realpath(os.path.dirname(__file__))
data_folder = os.path.join(script_folder, "data")

def iterate_files(path: str, recursive=False):
    # sorted, so that the order the tests end up running in is the same on
    # every machine: os.walk hands the files back in whatever order the
    # filesystem keeps them, and a failure that depends on the order is no fun
    # to chase when it only shows up on one checkout
    for subdir, _, files in os.walk(path):
        for file in sorted(files):
            yield os.path.join(subdir, file)
        if not recursive:
            break

def get_all_tests(fullpath):
    result = list()

    pattern = r"int TEST\s*\(([A-Za-z0-9_]+)\)\(.*\)"
    with open(fullpath, "r") as fin:
        for line in fin:
            data = re.findall(pattern, line)
            result.extend(data)
    return result

# Extensions of the files living in tests/data that are not samples, and thus
# must not be turned into a header.
NOT_A_SAMPLE = (".h", ".c", ".py", ".sh", ".md", ".json", ".gitignore")

def gen_data_header(sample: str):
    """Generate a C header embedding the content of a sample file.

    tests/data/<name>.<ext> becomes tests/data/<name>.h, exposing the sample
    as `static u8_t <name>[]`.
    """
    filename = os.path.basename(sample)
    name = os.path.splitext(filename)[0]
    outpath = os.path.join(os.path.dirname(sample), f"{name}.h")

    with open(sample, "rb") as fin:
        data = fin.read()

    guard = f"DATA_{name.upper()}_H"
    lines = [
        "/* Generated by tests/gen_tests.py. Do not edit. */\n",
        f"/* Source: tests/data/{filename} */\n",
        "\n",
        f"#ifndef {guard}\n",
        f"#define {guard}\n",
        "\n",
        "#include <defs.h>\n",
        "\n",
        "// clang-format off\n",
        f"static u8_t {name}[] = {{\n",
    ]
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        suffix = "," if i + 12 < len(data) else ""
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + suffix + "\n")
    lines.append("};\n")
    lines.append("// clang-format on\n")
    lines.append("\n")
    lines.append("#endif\n")

    content = "".join(lines)

    # Avoid touching the file when unchanged, so that incremental builds do
    # not rebuild the whole test suite.
    if os.path.exists(outpath):
        with open(outpath, "r") as fin:
            if fin.read() == content:
                return

    with open(outpath, "w") as fout:
        fout.write(content)

if __name__ == "__main__":
    for f in iterate_files(data_folder):
        if not os.path.basename(f).startswith(".") and not f.endswith(NOT_A_SAMPLE):
            gen_data_header(f)

    tests = list()
    for f in iterate_files(script_folder):
        dirname = os.path.dirname(f)
        basename = os.path.basename(f)
        if basename.startswith("test_"):
            name = basename
            test_names = get_all_tests(os.path.join(script_folder, f))
            tests.append((name, test_names))

    header  = '#include "t.h"\n\n'
    footer  = 'int main(int argc, char const* argv[])\n'
    footer += '{\n'
    footer += '    TESTS_MAIN_BODY(tests)\n'
    footer += '}\n'

    with open(os.path.join(script_folder, "main.c"), "w") as fout:
        fout.write(header)
        for fname, _ in tests:
            tname = fname.replace(".c", "").replace("test_", "")
            fout.write(f'#define TEST(n) {tname}_test_##n\n')
            fout.write(f'#include "{fname}"\n')
            fout.write(f'#undef TEST\n')
        fout.write('\n')
        fout.write('static test_t tests[] = {\n')
        for fname, test_names in tests:
            tname = fname.replace(".c", "").replace("test_", "")
            fout.write(f'#define TEST(n) {tname}_test_##n\n')
            for name in test_names:
                fout.write('    {"%s.%s", &TEST(%s)},\n' % (tname, name, name))
            fout.write(f'#undef TEST\n')

        fout.write('};\n\n')
        fout.write(footer)
