// Copyright (c) 2022-2026, bageyelet

/*  gen-grammar.js
 *  Generates syntaxes/bhe.tmLanguage.json from src/language.js.
 *
 *  The keyword, type and builtin lists live in exactly one place; run
 *  `npm run gen-grammar` after touching them. `npm test` fails when the
 *  checked-in grammar no longer matches what this script produces, so the two
 *  cannot drift apart.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const {
    KEYWORDS_CONTROL,
    KEYWORDS_DECL,
    KEYWORDS_MODIFIER,
    BUILTIN_TYPES,
    BUILTIN_FUNCTION_NAMES,
    SPECIAL_VARIABLES,
    SPECIAL_PROCS
} = require('../src/language');

const GRAMMAR_PATH = path.join(__dirname, '..', 'syntaxes', 'bhe.tmLanguage.json');

/** Longest first, so `u16` is never cut short by `u1`. */
const alt = (names) =>
    [...names]
        .sort((a, b) => b.length - a.length || a.localeCompare(b))
        .map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
        .join('|');

const IDENT = '[A-Za-z_][A-Za-z0-9_]*';

function buildGrammar() {
    return {
        $schema: 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
        name: 'BHE Binary Format Language',
        scopeName: 'source.bhe',
        fileTypes: ['bhe'],
        /* Generated by scripts/gen-grammar.js — edit that, not this file. */
        patterns: [
            { include: '#comments' },
            { include: '#strings' },
            { include: '#numbers' },
            { include: '#declarations' },
            { include: '#keywords' },
            { include: '#enum-access' },
            { include: '#import' },
            { include: '#builtins' },
            { include: '#calls' },
            { include: '#file-variables' },
            { include: '#types' },
            { include: '#special-variables' },
            { include: '#member-access' },
            { include: '#operators' },
            { include: '#punctuation' }
        ],
        repository: {
            comments: {
                patterns: [
                    { name: 'comment.line.double-slash.bhe', match: '//.*$' },
                    { name: 'comment.block.bhe', begin: '/\\*', end: '\\*/' }
                ]
            },

            /*  A string is `"[^"]*"`: there is no escape for the delimiter, so
             *  the next `"` always ends it. `\\"` inside a string therefore
             *  ends the string and leaves a stray backslash — flag it. */
            strings: {
                patterns: [
                    {
                        name: 'string.quoted.double.bhe',
                        begin: '"',
                        end: '"',
                        beginCaptures: { 0: { name: 'punctuation.definition.string.begin.bhe' } },
                        endCaptures: { 0: { name: 'punctuation.definition.string.end.bhe' } },
                        patterns: [
                            { name: 'constant.character.escape.bhe', match: '\\\\(?:x[0-9a-fA-F]{2}|[0rtn\\\\])' },
                            { name: 'invalid.illegal.unknown-escape.bhe', match: '\\\\.' }
                        ]
                    }
                ]
            },

            numbers: {
                patterns: [
                    {
                        name: 'constant.numeric.hex.bhe',
                        match: '\\b0[xX][0-9a-fA-F]+(?:[us](?:8|16|32|64))?\\b'
                    },
                    {
                        name: 'constant.numeric.decimal.bhe',
                        match: '\\b[0-9]+(?:[us](?:8|16|32|64))?\\b'
                    }
                ]
            },

            /*  Top-level declarations, so the name they introduce is scoped as
             *  a definition rather than as a plain identifier. */
            declarations: {
                patterns: [
                    {
                        match: `\\b(fn)\\s+(${IDENT})\\s*(\\()([^)]*)(\\))`,
                        captures: {
                            1: { name: 'keyword.declaration.function.bhe' },
                            2: { name: 'entity.name.function.bhe' },
                            3: { name: 'punctuation.section.parens.begin.bhe' },
                            4: { patterns: [{ name: 'variable.parameter.bhe', match: IDENT }] },
                            5: { name: 'punctuation.section.parens.end.bhe' }
                        }
                    },
                    {
                        match: `\\b(fn)\\s+(${IDENT})`,
                        captures: {
                            1: { name: 'keyword.declaration.function.bhe' },
                            2: { name: 'entity.name.function.bhe' }
                        }
                    },
                    {
                        /*  The body is scoped as a block of its own so the
                         *  members read as constants. The `{` may sit on the
                         *  next line, so it is not part of the begin match. */
                        begin: `\\b(enum|orenum)\\s+(${IDENT})\\s*(:)\\s*(${IDENT})\\b`,
                        beginCaptures: {
                            1: { name: 'keyword.declaration.enum.bhe' },
                            2: { name: 'entity.name.type.enum.bhe' },
                            3: { name: 'punctuation.separator.bhe' },
                            4: { patterns: [{ include: '#types' }] }
                        },
                        end: '\\}',
                        endCaptures: { 0: { name: 'punctuation.section.block.end.bhe' } },
                        patterns: [
                            { include: '#comments' },
                            { include: '#numbers' },
                            { name: 'variable.other.enummember.bhe', match: `\\b${IDENT}\\b` },
                            { include: '#operators' },
                            { include: '#punctuation' }
                        ]
                    },
                    {
                        match: `\\b(struct)\\s+(${IDENT})`,
                        captures: {
                            1: { name: 'keyword.declaration.struct.bhe' },
                            2: { name: 'entity.name.type.struct.bhe' }
                        }
                    },
                    {
                        /* `proc _identify` and `proc _identify_magic` are the
                         * two the `id` command looks for by name. */
                        match: `\\b(proc)\\s+(${alt(SPECIAL_PROCS)})\\b`,
                        captures: {
                            1: { name: 'keyword.declaration.proc.bhe' },
                            2: { name: 'support.function.identify.bhe' }
                        }
                    },
                    {
                        match: `\\b(proc)\\b(?:\\s+(${IDENT}))?`,
                        captures: {
                            1: { name: 'keyword.declaration.proc.bhe' },
                            2: { name: 'entity.name.function.proc.bhe' }
                        }
                    }
                ]
            },

            keywords: {
                patterns: [
                    { name: 'keyword.control.bhe', match: `\\b(?:${alt(KEYWORDS_CONTROL)})\\b` },
                    { name: 'storage.modifier.bhe', match: `\\b(?:${alt(KEYWORDS_MODIFIER)})\\b` },
                    { name: 'keyword.declaration.bhe', match: `\\b(?:${alt(KEYWORDS_DECL)})\\b` }
                ]
            },

            /* `gzip_flags_t::FNAME` */
            'enum-access': {
                patterns: [
                    {
                        match: `\\b(${IDENT})\\s*(::)\\s*(${IDENT})\\b`,
                        captures: {
                            1: { name: 'entity.name.type.bhe' },
                            2: { name: 'punctuation.accessor.bhe' },
                            3: { name: 'variable.other.enummember.bhe' }
                        }
                    }
                ]
            },

            /* `othertemplate#StructName` pulls a struct in from another file */
            import: {
                patterns: [
                    {
                        match: `\\b(${IDENT})\\s*(#)\\s*(${IDENT})\\b`,
                        captures: {
                            1: { name: 'entity.name.namespace.bhe' },
                            2: { name: 'punctuation.accessor.bhe' },
                            3: { name: 'entity.name.type.bhe' }
                        }
                    }
                ]
            },

            builtins: {
                patterns: [
                    {
                        name: 'support.function.builtin.bhe',
                        match: `\\b(?:${alt(BUILTIN_FUNCTION_NAMES)})\\b(?=\\s*\\()`
                    }
                ]
            },

            calls: {
                patterns: [{ name: 'entity.name.function.call.bhe', match: `\\b${IDENT}\\b(?=\\s*\\()` }]
            },

            /*  A file-variable declaration: `u32 length;`, `char type[4];`,
             *  `RGB entries[n];`. The trailing lookahead is what keeps this
             *  from swallowing ordinary pairs of identifiers. */
            'file-variables': {
                patterns: [
                    {
                        match: `\\b(${IDENT})\\s+(${IDENT})\\s*(?=[;\\[])`,
                        captures: {
                            1: { patterns: [{ include: '#types' }, { name: 'entity.name.type.bhe', match: '.+' }] },
                            2: { name: 'variable.other.member.bhe' }
                        }
                    }
                ]
            },

            types: {
                patterns: [
                    { name: 'storage.type.primitive.bhe', match: `\\b(?:${alt(BUILTIN_TYPES)})\\b` }
                ]
            },

            'special-variables': {
                patterns: [{ name: 'variable.language.bhe', match: `\\b(?:${alt(SPECIAL_VARIABLES)})\\b` }]
            },

            /* `header.e_ident.ei_class` */
            'member-access': {
                patterns: [
                    {
                        match: `(\\.)(${IDENT})\\b`,
                        captures: {
                            1: { name: 'punctuation.accessor.bhe' },
                            2: { name: 'variable.other.member.bhe' }
                        }
                    }
                ]
            },

            operators: {
                patterns: [
                    { name: 'keyword.operator.logical.bhe', match: '&&|\\|\\||!(?!=)' },
                    { name: 'keyword.operator.comparison.bhe', match: '==|!=|<=|>=|<(?![<])|>(?![>])' },
                    { name: 'keyword.operator.bitwise.bhe', match: '<<|>>|&|\\||\\^' },
                    { name: 'keyword.operator.arithmetic.bhe', match: '\\+|-|\\*|/|%' },
                    { name: 'keyword.operator.assignment.bhe', match: '=' }
                ]
            },

            punctuation: {
                patterns: [
                    { name: 'punctuation.section.block.begin.bhe', match: '\\{' },
                    { name: 'punctuation.section.block.end.bhe', match: '\\}' },
                    { name: 'punctuation.section.brackets.begin.bhe', match: '\\[' },
                    { name: 'punctuation.section.brackets.end.bhe', match: '\\]' },
                    { name: 'punctuation.section.parens.begin.bhe', match: '\\(' },
                    { name: 'punctuation.section.parens.end.bhe', match: '\\)' },
                    { name: 'punctuation.terminator.bhe', match: ';' },
                    { name: 'punctuation.separator.bhe', match: '[,:]' }
                ]
            }
        }
    };
}

const render = () => JSON.stringify(buildGrammar(), null, 2) + '\n';

if (require.main === module) {
    fs.writeFileSync(GRAMMAR_PATH, render());
    console.log(`wrote ${path.relative(process.cwd(), GRAMMAR_PATH)}`);
}

module.exports = { buildGrammar, render, GRAMMAR_PATH };
